version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    mem_limit: 256m
    command: -c fsync=off --client-min-messages=warning
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    restart: on-failure

volumes:
  pg_data:
