default: &default
  adapter: postgresql
  encoding: UTF8
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5433) %>
  user: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "postgres") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: technical_case_development

test:
  <<: *default
  database: technical_case_test

production:
  <<: *default
  database: technical_case_production
  username: technical_case
  password: <%= ENV["TECHNICAL_CASE_DATABASE_PASSWORD"] %>
